question_data = [
    {"text": "A slug's blood is green.", "answer": "True", "trivia": "The green color comes from the copper-based molecule, hemocyanin."},
    {"text": "The blue whale is the largest mammal on Earth.", "answer": "True", "trivia": "It's also the largest animal known to have ever existed."},
    {"text": "Owls are the only birds that can see the color blue.", "answer": "False", "trivia": "Owls actually cannot see the color blue."},
    {"text": "Sharks are immune to all known diseases.", "answer": "False", "trivia": "While sharks have strong immune systems, they are not immune to all diseases."},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True", "trivia": "Feet contain 26 bones, one-quarter of the total number in the human body."},
    {"text": "The total surface area of human lungs is the size of a football pitch.", "answer": "True", "trivia": "The lungs have a large surface area to maximize gas exchange."},
    {"text": "The Great Wall of China is visible from space.", "answer": "False", "trivia": "It is difficult to see the Great Wall with the naked eye from space."},
    {"text": "There are more stars in the universe than grains of sand on all the beaches on Earth.", "answer": "True", "trivia": "Estimates suggest there are more than 100 billion galaxies in the observable universe."},
    {"text": "Bananas are berries.", "answer": "True", "trivia": "In botanical terms, bananas qualify as berries because they are produced from a single ovary."},
    {"text": "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion of iron.", "answer": "True", "trivia": "Metal expands when heated and contracts when cooled."},
    {"text": "A group of flamingos is called a flamboyance.", "answer": "True", "trivia": "Flamingos are known for their distinctive pink color."},
    {"text": "Kangaroos cannot walk backwards.", "answer": "True", "trivia": "This is due to their muscular legs and large, powerful tail."},
    {"text": "All polar bears are left-handed.", "answer": "False", "trivia": "There is no evidence to suggest polar bears prefer one paw over the other."},
    {"text": "A newborn kangaroo is about the size of a lima bean.", "answer": "True", "trivia": "Newborn kangaroos, called joeys, are underdeveloped at birth."},
    {"text": "Dolphins sleep with one eye open.", "answer": "True", "trivia": "This allows them to remain vigilant for predators and other threats."},
    {"text": "A snail can sleep for 3 years straight.", "answer": "False", "trivia": "While snails can hibernate in unfavorable conditions, they do not sleep continuously for years."},
    {"text": "Cows moo with regional accents.", "answer": "True", "trivia": "Studies have shown that cows have distinct vocal patterns depending on their herd."},
    {"text": "An octopus has three hearts.", "answer": "True", "trivia": "Two of the hearts pump blood to the gills, while the third pumps it to the rest of the body."},
    {"text": "A group of crows is called a murder.", "answer": "True", "trivia": "This term dates back to the 15th century."},
    {"text": "Oysters can change gender multiple times in their lifespan.", "answer": "True", "trivia": "Oysters are known to be protandric hermaphrodites."},
    {"text": "Penguins propose to their mates with a pebble.", "answer": "True", "trivia": "Male penguins search for the smoothest, most perfect pebble to present to their prospective mate."},
    {"text": "A cockroach can live for a week without its head.", "answer": "True", "trivia": "They can survive for a period because they breathe through openings in their body segments."},
    {"text": "A group of rhinoceroses is called a crash.", "answer": "True", "trivia": "The term 'crash' refers to the potential sound made by a group of rhinos charging."},
    {"text": "Honey never spoils.", "answer": "True", "trivia": "Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still edible."},
    {"text": "The heart of a shrimp is located in its head.", "answer": "True", "trivia": "Shrimp have a complex circulatory system where their heart is situated near their brain."},
    {"text": "A group of frogs is called an army.", "answer": "True", "trivia": "This term reflects their tendency to move in a coordinated manner."},
    {"text": "The unicorn is the national animal of Scotland.", "answer": "True", "trivia": "It has been a symbol of Scotland for centuries."},
    {"text": "Mount Everest is the tallest mountain in the world.", "answer": "False", "trivia": "Mauna Kea in Hawaii is the tallest mountain when measured from its base on the ocean floor."},
    {"text": "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.", "answer": "True", "trivia": "The war is known as the Anglo-Zanzibar War."},
    {"text": "The first person to reach both the North and South Poles was Norwegian explorer Roald Amundsen.", "answer": "True", "trivia": "Amundsen reached the South Pole on December 14, 1911, and the North Pole on May 12, 1926."},
    {"text": "The tomato is a fruit.", "answer": "True", "trivia": "Botanically, tomatoes are classified as fruits because they develop from the ovary of a flower and contain seeds."},
    {"text": "The average person walks the equivalent of three times around the world in a lifetime.", "answer": "True", "trivia": "This is based on an average life expectancy and average steps per day."},
    {"text": "Cleopatra VII of Egypt lived closer in time to the first Moon landing than to the construction of the Great Pyramid of Giza.", "answer": "True", "trivia": "Cleopatra lived around 2,000 years ago, while the Great Pyramid was built around 4,500 years ago."},
    {"text": "The Eiffel Tower was originally intended for Barcelona, Spain, but the project was rejected.", "answer": "True", "trivia": "Gustave Eiffel then proposed it for Paris, where it was accepted and built."},
    {"text": "The first product to have a barcode was Wrigley's gum.", "answer": "True", "trivia": "It was scanned for the first time on June 26, 1974, at a Marsh supermarket in Ohio, USA."},
    {"text": "Octopuses have three hearts.", "answer": "True", "trivia": "Two pump blood to the gills, while the third pumps it to the rest of the body."},
    {"text": "The first oranges weren't orange.", "answer": "True", "trivia": "They were green, and in Chinese, the word for 'orange' means 'foreign orange'. They first grew in Southeast Asia."},
    {"text": "Lobsters can live to be over 100 years old.", "answer": "True", "trivia": "The oldest lobster ever caught was estimated to be 140 years old."},
    {"text": "A bolt of lightning is five times hotter than the sun.", "answer": "True", "trivia": "Lightning can heat the air around it to temperatures five times hotter than the surface of the sun."},
    {"text": "An average person will spend six months of their lifetime waiting for red lights to turn green.", "answer": "True", "trivia": "This statistic is based on estimates of time spent waiting at traffic lights."},
    {"text": "There are more lifeforms living on your skin than there are people on the planet.", "answer": "True", "trivia": "The human body is home to billions of microorganisms."},
    {"text": "A bolt of lightning is five times hotter than the sun.", "answer": "True", "trivia": "Lightning can heat the air around it to temperatures five times hotter than the surface of the sun."},
    {"text": "An average person will spend six months of their lifetime waiting for red lights to turn green.", "answer": "True", "trivia": "This statistic is based on estimates of time spent waiting at traffic lights."},
    {"text": "There are more lifeforms living on your skin than there are people on the planet.", "answer": "True", "trivia": "The human body is home to billions of microorganisms."}
]
